# Generated by Django 2.0.6 on 2018-07-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='study',
            name='certificate',
            field=models.CharField(max_length=150),
        ),
    ]
