# Generated by Django 2.0.6 on 2018-07-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunt', '0008_auto_20180711_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=10),
        ),
    ]
