# Generated by Django 2.0.6 on 2018-07-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunt', '0011_auto_20180711_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
