# Generated by Django 2.0.6 on 2018-08-02 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Volunt', '0013_authentaciton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authentaciton',
            new_name='Authentication',
        ),
    ]
