# Generated by Django 2.0.6 on 2018-08-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='up_date',
            field=models.DateField(),
        ),
    ]
