# Generated by Django 2.0.6 on 2018-08-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0002_auto_20180803_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='up_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
