# Generated by Django 2.0.6 on 2018-08-04 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0004_auto_20180804_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
