# Generated by Django 2.0.6 on 2018-08-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0005_auto_20180804_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='uploader',
            field=models.CharField(max_length=200),
        ),
    ]
